[package]
name = "lox"
version = "0.2.0"
authors = ["Jonathan Tran <jonnytran@gmail.com>"]
edition = "2018"

[dependencies]
argparse = "0.2.2"
fnv = "1.0.6"
lazy_static = "1.4.0"
unicode-segmentation = "1.3.0"
